### ISSUE TITLE
Unable to compile on VS 2019

### ISSUE THREAD

**Issue by EG-Julien** [iliasam/LDS01RR_lidar#2]
Hi,
I'm trying to compile your software with Visual Studio 2019.
The first problem that I got is : App.config is not present. I tried to create one with this content :
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<startup>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
	</startup>
</configuration>
```
This make the error disappear but once the program is running I can't get any data from it and it returns any error ...

![image](https://user-images.githubusercontent.com/20558227/201705299-93f5a29d-a4f2-42bc-8c5a-219bb0606a0a.png)

I have double checked that I got some raw data coming from my lidar (LDS01RR).

Do you have any idea or leads on the cause of the problem?

Thanks.

**Comment by iliasam** [comment]
Hello.
Thanks for your report, I added "App.config" to this repository.
But it is strange that your lidar is not working. 
I copied source code from this repository to another folder, build utility from that sources and checked working with my Lidar. 
It is working OK. 
You can try to check that serial port is selected well, and budrate at the "config.ini" is 115200.

**Comment by EG-Julien** [comment]
Hello.
I verified that my LiDAR is working properly. I'm using [this](https://github.com/getSurreal/XV_Lidar_Controller) firmware with an Arduino MEGA, perhaps there is an incompatibility ?
Did you build the app with VS Code 2019 ?
I double checked the baud rate in the config.ini file.
I didn't had try to recompile with the good App.config. I'm trying this evening and I'll keep you updated.

**Comment by iliasam** [comment]
You have mentioned that you are using firmware from here: https://github.com/getSurreal/XV_Lidar_Controller
But this software is designed for Neato Lidars (triangulation type) while mine software is designed for exact LDS01RR (produced by Roborock) - TOF Lidar.
So what type of the Lidar are you using?
I build my code with VS17.

**Comment by EG-Julien** [comment]
I'm using the LDS01RR form Roborock. I though these too LiDAR were working the same way. I got relatively consistent data with the firmware.
My LiDAR didn't come with any USB to UART bridge. And I couldn't find any documentation about one.
I assume that this is not an error from the software but the way I handle that "raw data" with my firmware.
Do you have any information about how it works ?

**Comment by iliasam** [comment]
If I'm not mistaken, LDS01RR is  have two variants: with development board - and without it.
Development board has its own MCU that is controlling speed and receiving data from the LIDAR rotating head and send in to the USB (using MCU USB hardware). I'm not sure if software of that MCU changing raw data from the head or not.
This board is like this one: https://github.com/Roborock-OpenSource/Cullinan but can have small changes.
Mine software is designed for Lidar with a such PCB.
